### ISSUE TITLE
 RazorPay Suddenly Stopped Working ( after working on Firebase Google Sign In? )

### ISSUE THREAD

**Issue by synapsecode** [razorpay/razorpay-flutter#137]
I integrated the standard code of RazorPay given in the example and it worked fine for a few days, Today i was working with Some Firebase Google Sign In Stuff and all of a sudden Razorpay does not work
(ANDROID)

Flutter Info
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.21296.1010], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.53.2)

Here is how i Imported Razorpay in Pubspec.yaml
razorpay_flutter:
    git:
      url: git://github.com/razorpay/razorpay-flutter.git
      ref: master

It was working fine. and all of a sudden it stopped working. Please help me to resolve this. Thanks

Here is the stack.
I/Timeline(19278): Timeline: Activity_launch_request time:3133989
W/ActivityThread(19278): handleWindowVisibility: no activity for token android.os.BinderProxy@d8cf33e
D/com.razorpay.checkout(19278): No permission for reading SMS
D/com.razorpay.checkout(19278): CheckoutActivity onCreate called
E/com.razorpay.checkout(19278): Error reading options!
E/com.razorpay.checkout(19278): org.json.JSONException: No value for send_sms_hash
E/com.razorpay.checkout(19278):         at org.json.JSONObject.get(JSONObject.java:392)
E/com.razorpay.checkout(19278):         at org.json.JSONObject.getBoolean(JSONObject.java:413)
E/com.razorpay.checkout(19278):         at com.razorpay.CheckoutOptions.shouldSendHashForSms(CheckoutOptions.java:36)
E/com.razorpay.checkout(19278):         at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:182)
E/com.razorpay.checkout(19278):         at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:102)
E/com.razorpay.checkout(19278):         at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
E/com.razorpay.checkout(19278):         at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
E/com.razorpay.checkout(19278):         at android.app.Activity.performCreate(Activity.java:7224)
E/com.razorpay.checkout(19278):         at android.app.Activity.performCreate(Activity.java:7213)
E/com.razorpay.checkout(19278):         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
E/com.razorpay.checkout(19278):         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
E/com.razorpay.checkout(19278):         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
E/com.razorpay.checkout(19278):         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/com.razorpay.checkout(19278):         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/com.razorpay.checkout(19278):         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/com.razorpay.checkout(19278):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
E/com.razorpay.checkout(19278):         at android.os.Handler.dispatchMessage(Handler.java:106)
E/com.razorpay.checkout(19278):         at android.os.Looper.loop(Looper.java:201)
E/com.razorpay.checkout(19278):         at android.app.ActivityThread.main(ActivityThread.java:6826)
E/com.razorpay.checkout(19278):         at java.lang.reflect.Method.invoke(Native Method)
E/com.razorpay.checkout(19278):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/com.razorpay.checkout(19278):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
W/System.err(19278): org.json.JSONException: No value for send_sms_hash
W/System.err(19278):    at org.json.JSONObject.get(JSONObject.java:392)
W/System.err(19278):    at org.json.JSONObject.getBoolean(JSONObject.java:413)
W/System.err(19278):    at com.razorpay.CheckoutOptions.shouldSendHashForSms(CheckoutOptions.java:36)
W/System.err(19278):    at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:182)
W/System.err(19278):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:102)
W/System.err(19278):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
W/System.err(19278):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(19278):    at android.app.Activity.performCreate(Activity.java:7224)
W/System.err(19278):    at android.app.Activity.performCreate(Activity.java:7213)
W/System.err(19278):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
W/System.err(19278):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
W/System.err(19278):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
W/System.err(19278):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
W/System.err(19278):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
W/System.err(19278):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
W/System.err(19278):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
W/System.err(19278):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(19278):    at android.os.Looper.loop(Looper.java:201)
W/System.err(19278):    at android.app.ActivityThread.main(ActivityThread.java:6826)
W/System.err(19278):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(19278):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err(19278):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
D/EgretLoader(19278): EgretLoader(Context context)
D/EgretLoader(19278): The context is not activity
D/com.razorpay.checkout(19278): Modified Url: https://api.razorpay.com/v1/checkout/public?version=1.6.5&library=checkoutjs&platform=android
W/System.err(19278): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/System.err(19278):    at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
W/System.err(19278):    at org.json.JSONTokener.nextValue(JSONTokener.java:94)
W/System.err(19278):    at org.json.JSONObject.<init>(JSONObject.java:159)
W/System.err(19278):    at org.json.JSONObject.<init>(JSONObject.java:176)
W/System.err(19278):    at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:195)
W/System.err(19278):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:102)
W/System.err(19278):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
W/System.err(19278):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(19278):    at android.app.Activity.performCreate(Activity.java:7224)
W/System.err(19278):    at android.app.Activity.performCreate(Activity.java:7213)
W/System.err(19278):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
W/System.err(19278):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
W/System.err(19278):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
W/System.err(19278):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
W/System.err(19278):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
W/System.err(19278):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
W/System.err(19278):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
W/System.err(19278):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(19278):    at android.os.Looper.loop(Looper.java:201)
W/System.err(19278):    at android.app.ActivityThread.main(ActivityThread.java:6826)
W/System.err(19278):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(19278):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err(19278):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
D/EgretLoader(19278): EgretLoader(Context context)
D/EgretLoader(19278): The context is not activity
D/EgretLoader(19278): EgretLoader(Context context)
D/EgretLoader(19278): The context is not activity
W/System.err(19278): java.lang.Exception: No dash options defined
W/System.err(19278):    at com.razorpay.CheckoutPresenterImpl.getProgressBarColor(CheckoutPresenterImpl.java:621)
W/System.err(19278):    at com.razorpay.BaseCheckoutActivity.createContainer(BaseCheckoutActivity.java:223)
W/System.err(19278):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:109)
W/System.err(19278):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
W/System.err(19278):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(19278):    at android.app.Activity.performCreate(Activity.java:7224)
W/System.err(19278):    at android.app.Activity.performCreate(Activity.java:7213)
W/System.err(19278):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
W/System.err(19278):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
W/System.err(19278):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
W/System.err(19278):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
W/System.err(19278):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
W/System.err(19278):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
W/System.err(19278):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
W/System.err(19278):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(19278):    at android.os.Looper.loop(Looper.java:201)
W/System.err(19278):    at android.app.ActivityThread.main(ActivityThread.java:6826)
W/System.err(19278):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(19278):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err(19278):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
W/System.err(19278): org.json.JSONException: No value for theme
W/System.err(19278):    at org.json.JSONObject.get(JSONObject.java:392)
W/System.err(19278):    at org.json.JSONObject.getJSONObject(JSONObject.java:612)
W/System.err(19278):    at com.razorpay.CheckoutPresenterImpl.getProgressBarColor(CheckoutPresenterImpl.java:606)
W/System.err(19278):    at com.razorpay.BaseCheckoutActivity.createContainer(BaseCheckoutActivity.java:223)
W/System.err(19278):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:109)
W/System.err(19278):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
W/System.err(19278):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(19278):    at android.app.Activity.performCreate(Activity.java:7224)
W/System.err(19278):    at android.app.Activity.performCreate(Activity.java:7213)
W/System.err(19278):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
W/System.err(19278):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
W/System.err(19278):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
W/System.err(19278):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
W/System.err(19278):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
W/System.err(19278):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
W/System.err(19278):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
W/System.err(19278):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(19278):    at android.os.Looper.loop(Looper.java:201)
W/System.err(19278):    at android.app.ActivityThread.main(ActivityThread.java:6826)
W/System.err(19278):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(19278):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err(19278):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
D/com.razorpay.checkout(19278): OTPElf Constructor
D/com.razorpay.checkout(19278): No permission for reading SMS
D/com.razorpay.checkout(19278): OTPElf Constructor
D/com.razorpay.checkout(19278): No permission for reading SMS
D/com.razorpay.checkout(19278): NOT FULLSCREEN
D/EgretLoader(19278): EgretLoader(Context context)
D/EgretLoader(19278): The context is not activity
W/ContentCatcher(19278): Failed to notify a WebView
W/ContentCatcher(19278): Failed to notify a WebView
D/com.razorpay.checkout(19278): Updating OTPElf
D/com.razorpay.checkout(19278): Updating OTPElf
D/com.razorpay.checkout(19278): RzpAssist onPageStarted: https://api.razorpay.com/v1/checkout/public?version=1.6.5&library=checkoutjs&platform=android
E/com.razorpay.checkout(19278): Webview JS Error: Uncaught SyntaxError: Invalid or unexpected token
I/chromium(19278): [INFO:CONSOLE(1)] "Uncaught SyntaxError: Invalid or unexpected token", source: https://checkout.razorpay.com/v1/checkout-frame.js (1)
D/com.razorpay.checkout(19278): Checkout loaded in 0.37 sec.
D/com.razorpay.checkout(19278): not magic
E/com.razorpay.checkout(19278): Webview JS Error: Uncaught SyntaxError: Invalid or unexpected token
I/chromium(19278): [INFO:CONSOLE(1)] "Uncaught SyntaxError: Invalid or unexpected token", source: https://api.razorpay.com/v1/checkout/public?version=1.6.5&library=checkoutjs&platform=android (1)
W/System.err(19278): javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
W/System.err(19278):    at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
W/System.err(19278):    at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:596)
W/System.err(19278):    at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:363)
W/System.err(19278):    at javax.crypto.Cipher.doFinal(Cipher.java:2055)
W/System.err(19278):    at com.razorpay.CryptLib.encryptDecrypt(CryptLib.java:176)
W/System.err(19278):    at com.razorpay.CryptLib.decrypt(CryptLib.java:269)
W/System.err(19278):    at com.razorpay.BaseUtils.decryptFile(BaseUtils.java:719)
W/System.err(19278):    at com.razorpay.OtpElfData$2.run(OtpElfData.java:55)
W/System.err(19278):    at com.razorpay.Owl.onPostExecute(Owl.java:137)
W/System.err(19278):    at com.razorpay.Owl.onPostExecute(Owl.java:23)
W/System.err(19278):    at android.os.AsyncTask.finish(AsyncTask.java:695)
W/System.err(19278):    at android.os.AsyncTask.access$600(AsyncTask.java:180)
W/System.err(19278):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
W/System.err(19278):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(19278):    at android.os.Looper.loop(Looper.java:201)
W/System.err(19278):    at android.app.ActivityThread.main(ActivityThread.java:6826)
W/System.err(19278):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(19278):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err(19278):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
D/com.razorpay.checkout(19278): Unable to decrypt file, error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
W/System.err(19278): javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
W/System.err(19278):    at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
W/System.err(19278):    at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:596)
W/System.err(19278):    at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:363)
W/System.err(19278):    at javax.crypto.Cipher.doFinal(Cipher.java:2055)
W/System.err(19278):    at com.razorpay.CryptLib.encryptDecrypt(CryptLib.java:176)
W/System.err(19278):    at com.razorpay.CryptLib.decrypt(CryptLib.java:269)
W/System.err(19278):    at com.razorpay.BaseUtils.decryptFile(BaseUtils.java:719)
W/System.err(19278):    at com.razorpay.OtpElfData$2.run(OtpElfData.java:55)
W/System.err(19278):    at com.razorpay.Owl.onPostExecute(Owl.java:137)
W/System.err(19278):    at com.razorpay.Owl.onPostExecute(Owl.java:23)
W/System.err(19278):    at android.os.AsyncTask.finish(AsyncTask.java:695)
W/System.err(19278):    at android.os.AsyncTask.access$600(AsyncTask.java:180)
W/System.err(19278):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
W/System.err(19278):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(19278):    at android.os.Looper.loop(Looper.java:201)
W/System.err(19278):    at android.app.ActivityThread.main(ActivityThread.java:6826)
W/System.err(19278):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(19278):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err(19278):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
D/com.razorpay.checkout(19278): Unable to decrypt file, error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
W/System.err(19278): javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
W/System.err(19278):    at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
W/System.err(19278):    at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:596)
W/System.err(19278):    at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:363)
W/System.err(19278):    at javax.crypto.Cipher.doFinal(Cipher.java:2055)
W/System.err(19278):    at com.razorpay.CryptLib.encryptDecrypt(CryptLib.java:176)
W/System.err(19278):    at com.razorpay.CryptLib.decrypt(CryptLib.java:269)
W/System.err(19278):    at com.razorpay.BaseUtils.decryptFile(BaseUtils.java:719)
W/System.err(19278):    at com.razorpay.MagicData$2.run(MagicData.java:41)
W/System.err(19278):    at com.razorpay.Owl.onPostExecute(Owl.java:137)
W/System.err(19278):    at com.razorpay.Owl.onPostExecute(Owl.java:23)
W/System.err(19278):    at android.os.AsyncTask.finish(AsyncTask.java:695)
W/System.err(19278):    at android.os.AsyncTask.access$600(AsyncTask.java:180)
W/System.err(19278):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
W/System.err(19278):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(19278):    at android.os.Looper.loop(Looper.java:201)
W/System.err(19278):    at android.app.ActivityThread.main(ActivityThread.java:6826)
W/System.err(19278):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(19278):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err(19278):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
D/com.razorpay.checkout(19278): Unable to decrypt file, error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E/com.razorpay.checkout(19278): Webview JS Error: Uncaught TypeError: window.getDeviceDetails is not a function
I/chromium(19278): [INFO:CONSOLE(1)] "Uncaught TypeError: window.getDeviceDetails is not a function", source: https://api.razorpay.com/v1/checkout/public?version=1.6.5&library=checkoutjs&platform=android (1)

**Comment by sumedht** [comment]
@synapsecode It's fixed now & working!

**Comment by synapsecode** [comment]
Thank you @sumedht for your quick response and assistance! It is working now.
Could you please elaborate why the error occurred for future reference and learning?
That'd be great. Thanks

**Comment by Nautiyalsachin** [comment]
@synapsecode There was an internal error which caused this, we have fixed it as soon as we got to know about it. Closing this issue now. Feel free to add more comments here or re-opening the issue.
