### ISSUE TITLE
App crashing after payment in One plus and Oppo device(Android 10)

### ISSUE THREAD

**Issue by Aj4Android** [razorpay/razorpay-flutter#153]
Below is the error log shown by Firebase Crashlytics:
1) Please look into this issue and I am usinf 1.2.3 version of RazorPay.

Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=62442, result=1, data=Intent { (has extras) }} to activity {com.kizo.kizo/com.kizo.kizo.MainActivity}: java.lang.IllegalStateException: Reply already submitted
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4963)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5004)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7697)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
       
       Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.a(ContactsServicePlugin.java:4)
       at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$BaseContactsServiceDelegate.onActivityResult(ContactsServicePlugin.java:88)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:15)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:10)
       at android.app.Activity.dispatchActivityResult(Activity.java:8135)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4956)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5004)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7697)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by sumedht** [comment]
@Aj4Android From the crash log it doesn't look like it's from the Razorpay side. Can we have more details like SDK version, scenario to reproduced?

**Comment by Aj4Android** [comment]
> @Aj4Android From the crash log it doesn't look like it's from the Razorpay side. Can we have more details like SDK version, scenario to reproduced?

RazorPay is working very well for all other Android devices but only One plus 5 & Oppo with Android 10 upgrade showed the crash when user makes successful payment & comes back to the app but app is already destroyed so at the end whole app gets terminated

**Comment by Nautiyalsachin** [comment]
@Aj4Android Closing this issue due to inactivity, feel free to add more comments or re-opening it.
