### ISSUE TITLE
No permission for reading SMS and error reading options with exception No value for send_sms_hash

### ISSUE THREAD

**Issue by gouthamravella** [razorpay/razorpay-flutter#159]
I am getting this error which is breaking the code.

Full details:

```
No permission for reading SMS
D/com.razorpay.checkout(21887): CheckoutActivity onCreate called
E/com.razorpay.checkout(21887): Error reading options!
E/com.razorpay.checkout(21887): org.json.JSONException: No value for send_sms_hash
E/com.razorpay.checkout(21887):         at org.json.JSONObject.get(JSONObject.java:400)
E/com.razorpay.checkout(21887):         at org.json.JSONObject.getBoolean(JSONObject.java:421)
E/com.razorpay.checkout(21887):         at com.razorpay.CheckoutOptions.shouldSendHashForSms(CheckoutOptions.java:36)
E/com.razorpay.checkout(21887):         at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:181)
E/com.razorpay.checkout(21887):         at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:103)
E/com.razorpay.checkout(21887):         at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
E/com.razorpay.checkout(21887):         at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
E/com.razorpay.checkout(21887):         at android.app.Activity.performCreate(Activity.java:8151)
E/com.razorpay.checkout(21887):         at android.app.Activity.performCreate(Activity.java:8135)
E/com.razorpay.checkout(21887):         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/com.razorpay.checkout(21887):         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)
E/com.razorpay.checkout(21887):         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
E/com.razorpay.checkout(21887):         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/com.razorpay.checkout(21887):         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/com.razorpay.checkout(21887):         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/com.razorpay.checkout(21887):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
E/com.razorpay.checkout(21887):         at android.os.Handler.dispatchMessage(Handler.java:106)
E/com.razorpay.checkout(21887):         at android.os.Looper.loop(Looper.java:255)
E/com.razorpay.checkout(21887):         at android.app.ActivityThread.main(ActivityThread.java:8214)
E/com.razorpay.checkout(21887):         at java.lang.reflect.Method.invoke(Native Method)
E/com.razorpay.checkout(21887):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/com.razorpay.checkout(21887):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
W/System.err(21887): org.json.JSONException: No value for send_sms_hash
W/System.err(21887):    at org.json.JSONObject.get(JSONObject.java:400)
W/System.err(21887):    at org.json.JSONObject.getBoolean(JSONObject.java:421)
W/System.err(21887):    at com.razorpay.CheckoutOptions.shouldSendHashForSms(CheckoutOptions.java:36)
W/System.err(21887):    at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:181)
W/System.err(21887):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:103)
W/System.err(21887):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
W/System.err(21887):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8151)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8135)
W/System.err(21887):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
W/System.err(21887):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)
W/System.err(21887):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err(21887):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
W/System.err(21887):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(21887):    at android.os.Looper.loop(Looper.java:255)
W/System.err(21887):    at android.app.ActivityThread.main(ActivityThread.java:8214)
W/System.err(21887):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21887):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
W/System.err(21887):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
W/System.err(21887): java.lang.SecurityException: getDataNetworkTypeForSubscriber
W/System.err(21887):    at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
W/System.err(21887):    at android.os.Parcel.createException(Parcel.java:2373)
W/System.err(21887):    at android.os.Parcel.readException(Parcel.java:2356)
W/System.err(21887):    at android.os.Parcel.readException(Parcel.java:2298)
W/System.err(21887):    at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
W/System.err(21887):    at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
W/System.err(21887):    at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
W/System.err(21887):    at com.razorpay.BaseUtils.getCellularNetworkType(BaseUtils.java:313)
W/System.err(21887):    at com.razorpay.Lumberjack.setNetworkDetails(Lumberjack.java:84) 
W/System.err(21887):    at com.razorpay.Lumberjack.setBaseImportJSON(Lumberjack.java:180)
W/System.err(21887):    at com.razorpay.Lumberjack.init(Lumberjack.java:370)
W/System.err(21887):    at com.razorpay.AnalyticsUtil.init(AnalyticsUtil.java:63)        
W/System.err(21887):    at com.razorpay.AnalyticsUtil.setup(AnalyticsUtil.java:53)       
W/System.err(21887):    at com.razorpay.CheckoutUtils.addAddons(CheckoutUtils.java:50)
W/System.err(21887):    at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:186)
W/System.err(21887):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:103)
W/System.err(21887):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
W/System.err(21887):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8151)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8135)
W/System.err(21887):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
W/System.err(21887):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)
W/System.err(21887):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
W/System.err(21887):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err(21887):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
W/System.err(21887):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(21887):    at android.os.Looper.loop(Looper.java:255)
W/System.err(21887):    at android.app.ActivityThread.main(ActivityThread.java:8214)
W/System.err(21887):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21887):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
W/System.err(21887):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
I/WebViewFactory(21887): Loading com.google.android.webview version 88.0.4324.141 (code 432414133)
W/com.mobile.mig(21887): Insufficient pre-allocated space to mmap vdex.
W/com.mobile.mig(21887): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/com.mobile.mig(21887): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)    
W/com.mobile.mig(21887): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/com.mobile.mig(21887): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/com.mobile.mig(21887): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)I/cr_LibraryLoader(21887): Loaded native library version number "88.0.4324.141"
I/cr_CachingUmaRecorder(21887): Flushed 4 samples from 4 histograms.
D/com.razorpay.checkout(21887): {"key":"some_key","events":[],"context":{"mode":"test","device":{"manufacturer":"OPPO","model":"CPH","name":"OP4863","type":"phone","version":"Android11","OPPO":"OPPO","CPH":"CPH1969","device_size":"1080w X 2208h","device_resolution":"1080x2208x480"},"sdk":{"version":"1.6.6","type":"checkout"}},"screen":{"density":3,"width":1080,"height":2208},"locale":"en-US","timezone":"Asia\/Kolkata","user_agent":"Dalvik\/2.1.0 (Linux; U; Android 11; CPH12 
Build\/RP1A.200720.011)","webview_user_agent":"Mozilla\/5.0 (Linux; Android 11; CPH12 Build\/RP1A.200720.011; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/88.0.4324.141 Mobile Safari\/537.36"}}
D/com.razorpay.checkout(21887): Modified Url: https://api.razorpay.com/v1/checkout/public?version=1.6.6&library=checkoutjs&platform=android
W/System.err(21887): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/System.err(21887):    at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:121)
W/System.err(21887):    at org.json.JSONTokener.nextValue(JSONTokener.java:98)
W/System.err(21887):    at org.json.JSONObject.<init>(JSONObject.java:165)
W/System.err(21887):    at org.json.JSONObject.<init>(JSONObject.java:182)
W/System.err(21887):    at com.razorpay.CheckoutPresenterImpl.setOptions(CheckoutPresenterImpl.java:193)
W/System.err(21887):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:103)
W/System.err(21887):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
W/System.err(21887):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8151)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8135)
W/System.err(21887):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
W/System.err(21887):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)
W/System.err(21887):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
W/System.err(21887):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err(21887):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
W/System.err(21887):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(21887):    at android.os.Looper.loop(Looper.java:255)
W/System.err(21887):    at android.app.ActivityThread.main(ActivityThread.java:8214)
W/System.err(21887):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21887):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
W/System.err(21887):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
W/System.err(21887): java.lang.Exception: No dash options defined
W/System.err(21887):    at com.razorpay.CheckoutPresenterImpl.getProgressBarColor(CheckoutPresenterImpl.java:614)
W/System.err(21887):    at com.razorpay.BaseCheckoutActivity.createContainer(BaseCheckoutActivity.java:224)
W/System.err(21887):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:110)
W/System.err(21887):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
W/System.err(21887):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8151)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8135)
W/System.err(21887):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
W/System.err(21887):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)
W/System.err(21887):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
W/System.err(21887):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err(21887):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
W/System.err(21887):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(21887):    at android.os.Looper.loop(Looper.java:255)
W/System.err(21887):    at android.app.ActivityThread.main(ActivityThread.java:8214)
W/System.err(21887):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21887):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
W/System.err(21887):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
W/System.err(21887): org.json.JSONException: No value for theme
W/System.err(21887):    at org.json.JSONObject.get(JSONObject.java:400)
W/System.err(21887):    at org.json.JSONObject.getJSONObject(JSONObject.java:620)
W/System.err(21887):    at com.razorpay.CheckoutPresenterImpl.getProgressBarColor(CheckoutPresenterImpl.java:599)
W/System.err(21887):    at com.razorpay.BaseCheckoutActivity.createContainer(BaseCheckoutActivity.java:224)
W/System.err(21887):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:110)
W/System.err(21887):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
W/System.err(21887):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8151)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8135)
W/System.err(21887):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
W/System.err(21887):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)
W/System.err(21887):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
W/System.err(21887):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err(21887):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
W/System.err(21887):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(21887):    at android.os.Looper.loop(Looper.java:255)
W/System.err(21887):    at android.app.ActivityThread.main(ActivityThread.java:8214)
W/System.err(21887):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21887):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
W/System.err(21887):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
D/com.razorpay.checkout(21887): OTPElf Constructor
D/com.razorpay.checkout(21887): No permission for reading SMS
D/com.razorpay.checkout(21887): OTPElf Constructor
D/com.razorpay.checkout(21887): No permission for reading SMS
W/com.mobile.mig(21887): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
I/System.out(21887): [socket]:check permission begin!
D/libMEOW (21887): applied 1 plugins for [com.mobile.migo]:
D/libMEOW (21887):   plugin 1: [libMEOW_gift.so]:
W/cr_media(21887): Requires BLUETOOTH permission
E/libEGL  (21887): Invalid file path for libcolorx-loader.so
E/libEGL  (21887): Invalid file path for libcolorx-loader.so
I/libMEOW_gift(21887): ctx:0xb40000779c9850b0, ARC not Enabled.
E/libEGL  (21887): Invalid file path for libcolorx-loader.so
I/chatty  (21887): uid=10675(com.mobile.migo) Chrome_InProcGp identical 2 lines
E/libEGL  (21887): Invalid file path for libcolorx-loader.so
D/com.razorpay.checkout(21887): NOT FULLSCREEN
W/System.err(21887): java.lang.SecurityException: getDataNetworkTypeForSubscriber
W/System.err(21887):    at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
W/System.err(21887):    at android.os.Parcel.createException(Parcel.java:2373)
W/System.err(21887):    at android.os.Parcel.readException(Parcel.java:2356)
W/System.err(21887):    at android.os.Parcel.readException(Parcel.java:2298)
W/System.err(21887):    at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
W/System.err(21887):    at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
W/System.err(21887):    at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
W/System.err(21887):    at com.razorpay.BaseUtils.getCellularNetworkType(BaseUtils.java:313)
W/System.err(21887):    at com.razorpay.BaseConfig.getFetchConfigBuilder(BaseConfig.java:346)
W/System.err(21887):    at com.razorpay.Config.getFetchConfigUrl(Config.java:269)
W/System.err(21887):    at com.razorpay.Config.fetchConfig(Config.java:256)
W/System.err(21887):    at com.razorpay.CheckoutPresenterImpl.fetchCondfig(CheckoutPresenterImpl.java:473)
W/System.err(21887):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:148)
W/System.err(21887):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
W/System.err(21887):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8151)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8135)
W/System.err(21887):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
W/System.err(21887):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)
W/System.err(21887):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
W/System.err(21887):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err(21887):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
W/System.err(21887):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(21887):    at android.os.Looper.loop(Looper.java:255)
W/System.err(21887):    at android.app.ActivityThread.main(ActivityThread.java:8214)
W/System.err(21887):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21887):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
W/System.err(21887):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
W/System.err(21887): java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
W/System.err(21887):    at android.app.ContextImpl.checkMode(ContextImpl.java:2939)
W/System.err(21887):    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:508)
W/System.err(21887):    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:498)
W/System.err(21887):    at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:198)
W/System.err(21887):    at com.razorpay.SharedPreferenceUtil.getPublicPrefs(SharedPreferenceUtil.java:63)
W/System.err(21887):    at com.razorpay.CardSaving.getDeviceToken(CardSaving.java:265)
W/System.err(21887):    at com.razorpay.CardSaving.fetchDeviceTokenFromOtherAppsIfRequired(CardSaving.java:167)
W/System.err(21887):    at com.razorpay.CheckoutPresenterImpl.handleCardSaving(CheckoutPresenterImpl.java:370)
W/System.err(21887):    at com.razorpay.BaseCheckoutActivity.onCreate(BaseCheckoutActivity.java:149)
W/System.err(21887):    at com.razorpay.BaseCheckoutOtpelfActivity.onCreate(BaseCheckoutOtpelfActivity.java:23)
W/System.err(21887):    at com.razorpay.CheckoutActivity.onCreate(CheckoutActivity.java:8)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8151)
W/System.err(21887):    at android.app.Activity.performCreate(Activity.java:8135)
W/System.err(21887):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
W/System.err(21887):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)
W/System.err(21887):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
W/System.err(21887):    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err(21887):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err(21887):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
W/System.err(21887):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(21887):    at android.os.Looper.loop(Looper.java:255)
W/System.err(21887):    at android.app.ActivityThread.main(ActivityThread.java:8214)
W/System.err(21887):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21887):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
W/System.err(21887):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
V/PhoneWindow(21887): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@59b6e0a[]
```

Flutter Version: 2.0.3

**Comment by vivekshindhe** [comment]
@gouthamravella We have a lot of options you could send in the payload here. send_sms_hash, theme, dash are a few examples. We do this to keep the user informed about these. These aren't fatal errors. This won't affect the User Experience  or breakage. Please don't worry about these. Closing the ticket. Please reply here or create another ticket if you are facing another issue. 
Thank you.

**Comment by gouthamravella** [comment]
This issue is causing the app shutdown when reading sms automatically in bank otp verification page. 
Here are the below details:

I/OpenGLRenderer(26405): 
D/AndroidRuntime(26405): Shutting down VM
E/AndroidRuntime(26405): FATAL EXCEPTION: main
E/AndroidRuntime(26405): Process: com.mobile.companyname, PID: 26405
E/AndroidRuntime(26405): java.lang.RuntimeException: Unable to start receiver com.oohyugi.sms_otp_auto_verify.SmsBroadcastReceiver: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
E/AndroidRuntime(26405):        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4376)
E/AndroidRuntime(26405):        at android.app.ActivityThread.access$1700(ActivityThread.java:287)
E/AndroidRuntime(26405):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2170)
E/AndroidRuntime(26405):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(26405):        at android.os.Looper.loop(Looper.java:255)
E/AndroidRuntime(26405):        at android.app.ActivityThread.main(ActivityThread.java:8214)
E/AndroidRuntime(26405):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26405):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
E/AndroidRuntime(26405):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
E/AndroidRuntime(26405): Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
E/AndroidRuntime(26405):        at com.oohyugi.sms_otp_auto_verify.SmsBroadcastReceiver.onReceive(SmsBroadcastReceiver.kt:28)
E/AndroidRuntime(26405):        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4360)
E/AndroidRuntime(26405):        ... 8 more
D/com.razorpay.checkout(26405): java.lang.RuntimeException: Unable to start receiver com.oohyugi.sms_otp_auto_verify.SmsBroadcastReceiver: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
D/com.razorpay.checkout(26405):         at android.app.ActivityThread.handleReceiver(ActivityThread.java:4376)
D/com.razorpay.checkout(26405):         at android.app.ActivityThread.access$1700(ActivityThread.java:287)
D/com.razorpay.checkout(26405):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2170)
D/com.razorpay.checkout(26405):         at android.os.Handler.dispatchMessage(Handler.java:106)
D/com.razorpay.checkout(26405):         at android.os.Looper.loop(Looper.java:255)
D/com.razorpay.checkout(26405):         at android.app.ActivityThread.main(ActivityThread.java:8214)
D/com.razorpay.checkout(26405):         at java.lang.reflect.Method.invoke(Native Method)
D/com.razorpay.checkout(26405):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
D/com.razorpay.checkout(26405):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
D/com.razorpay.checkout(26405): Caused by: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.String
D/com.razorpay.checkout(26405):         at com.oohyugi.sms_otp_auto_verify.SmsBroadcastReceiver.onReceive(SmsBroadcastReceiver.kt:28)
D/com.razorpay.checkout(26405):         at android.app.ActivityThread.handleReceiver(ActivityThread.java:4360)
D/com.razorpay.checkout(26405):         ... 8 more
I/Process (26405): Sending signal. PID: 26405 SIG: 9
Lost connection to device.

Please resolve this issue as soon as possible. Thanks.

**Comment by developsolutions** [comment]
Any resolution to this issue yet? Let me know please?

**Comment by anup-geeky** [comment]
@gouthamravella @vivekshindhe  Any solution? I'm facing same issue

**Comment by developsolutions** [comment]
I cant remember. But I think that error is on the emulator only.

**Comment by umeshrane17** [comment]
This library sms_otp_auto_verify is causing the issue. Remove this from your dependency
