### ISSUE TITLE
App crashing in some android devices

### ISSUE THREAD

**Issue by imSanjaySoni** [razorpay/razorpay-flutter#165]
**Caused by java.lang.IllegalArgumentException
Service not registered: com.razorpay.AdvertisingIdUtil$AdvertisingConnection@4a5809b
com.razorpay.AdvertisingIdUtil$AdvertisingIdAsyncTask.doInBackground
**
```
Caused by java.lang.IllegalArgumentException: Service not registered: com.razorpay.AdvertisingIdUtil$AdvertisingConnection@4a5809b
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1570)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1702)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:727)
       at com.razorpay.AdvertisingIdUtil$AdvertisingIdAsyncTask.doInBackground(AdvertisingIdUtil.java:47)
       at com.razorpay.AdvertisingIdUtil$AdvertisingIdAsyncTask.doInBackground(AdvertisingIdUtil.java:26)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

## Flutter Version :
2.0.5 stable

## Cocoapod Version :
   pod version 13
  razorpay_flutter: ^1.2.2

**Comment by sumedht** [comment]
@imSanjaySoni Can u update to the latest version of flutter SDK? It should not give this issue in a newer version of SDK.

**Comment by imSanjaySoni** [comment]
Do you mean Flutter  2.0.6 stable?

**Comment by sumedht** [comment]
@imSanjaySoni Newer version of razorpay-flutter SDK, v1.2.6

**Comment by imSanjaySoni** [comment]
> @imSanjaySoni Newer version of razorpay-flutter SDK, v1.2.6
I can't, Razorpay-flutter SDK, v1.2.6 is null safety enabled but our project is still not migrated to null safety because some packages which I have used are not migrated to null safety.

**Comment by sumedht** [comment]
@imSanjaySoni Right now the solution is to update to the latest version only. U have to update ur dependencies to null safety only.
