### ISSUE TITLE
Seeing Crashes On Android

### ISSUE THREAD

**Issue by madhu6264** [razorpay/razorpay-flutter#192]
Non-fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=62442, result=0, data=null} to activity {com.bedwal.bijak.mvp/com.bedwal.bijak.mvp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5319)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5360)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:239)
       at android.app.ActivityThread.main(ActivityThread.java:8100)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
5:13
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
       at com.razorpay.Checkout.handleActivityResult(Checkout.java:641)
       at com.razorpay.razorpay_flutter.RazorpayDelegate.onActivityResult(RazorpayDelegate.java:129)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
       at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:769)
       at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:509)
       at android.app.Activity.dispatchActivityResult(Activity.java:8415)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5312)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5360)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:239)
       at android.app.ActivityThread.main(ActivityThread.java:8100)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
<img width="1331" alt="Screenshot 2021-08-19 at 5 13 36 PM" src="https://user-images.githubusercontent.com/10560724/130063392-5404efee-37c6-4d73-b52b-221540b8990d.png">

**Comment by hemantgarg67** [comment]
resolved?

**Comment by paddy57** [comment]
@hemantgarg67 @madhu6264 are you able to resolve this ?

**Comment by i-m-aman** [comment]
Any solution guys? I am getting this crash every day in crashlystics.

**Comment by sumedht** [comment]
@madhu6264 Any steps to reproduce it would be helpful

**Comment by paddy57** [comment]
Any solution yet, seeing same crash on firebase crashanalytics. 
@sumedht I think crash happens when we call _razorpay.open.

**Comment by yogesh-wittyfeed** [comment]
Getting this crash when we call _razorpay.open. Multiple crashes log on play-store

java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5541)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:5582)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:51)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2317)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8595)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.NullPointerException: 
  at com.razorpay.Checkout.handleActivityResult (Checkout.java:641)
  at com.razorpay.razorpay_flutter.RazorpayDelegate.onActivityResult (RazorpayDelegate.java:129)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult (FlutterEngineConnectionRegistry.java:741)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult (FlutterEngineConnectionRegistry.java:426)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult (FlutterActivityAndFragmentDelegate.java:749)
  at io.flutter.embedding.android.FlutterFragment.onActivityResult (FlutterFragment.java:916)
  at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult (FlutterFragmentActivity.java:534)
  at android.app.Activity.dispatchActivityResult (Activity.java:8550)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5534)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:5582)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:51)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2317)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8595)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

**Comment by gouravd** [comment]
Is anyone looking into this?

**Comment by sachi097** [comment]
Facing the same issue. Any solution please.

**Comment by 876arham** [comment]
Is this resolved,any update?
