### ISSUE TITLE
App crashes when try to open razorpay windows

### ISSUE THREAD

**Issue by itspwk** [razorpay/razorpay-flutter#237]
I have razorpay_flutter 1.2.9, When I try to open razorpay checkout app crashes with below error : 

`W/System.err(18248): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
W/System.err(18248): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(18248): 	at android.os.Looper.loop(Looper.java:223)
W/System.err(18248): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err(18248): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18248): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err(18248): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
W/System.err(18248): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.nbu.paisa.inapp.client.api.PaymentsClient" on path: DexPathList`

My flutter doctor result is 
`[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.434], locale en-IN)
    • Flutter version 2.8.1 at D:\developments\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\pawan\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\pawan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 96.0.1054.62

• No issues found!`

**Comment by sumedht** [comment]
@itspwk Have u added proguard rule in app listed [here](https://razorpay.com/docs/payments/payment-gateway/android-integration/standard/#proguard-rules)

**Comment by itspwk** [comment]
> @itspwk Have u added proguard rule in app listed [here](https://razorpay.com/docs/payments/payment-gateway/android-integration/standard/#proguard-rules)

Yes, I added these rules.

**Comment by wa11breaker** [comment]
@sumedht 
Try removing the order_id 
```
    var options = {
      'key': '<Key>',
      'amount': 5000,
      'name': '<Name>',
      'description': <description>,
      // 'order_id': orderId,
      'prefill': {'contact': '1234567890, 'email': 'someone@email.com'},
    };
    _razorpay.open(options);
  ```

**Comment by itspwk** [comment]
> @sumedht Try removing the order_id
> 
> ```
>     var options = {
>       'key': '<Key>',
>       'amount': 5000,
>       'name': '<Name>',
>       'description': <description>,
>       // 'order_id': orderId,
>       'prefill': {'contact': '1234567890, 'email': 'someone@email.com'},
>     };
>     _razorpay.open(options);
> ```

Still same problem

**Comment by Suheb786** [comment]
Same here i think this problem could be in this latest version

**Comment by itspwk** [comment]
hey Razorpay team,

Do you have any solution for this.

**Comment by harshuhere01** [comment]
i'm also facing same issue, tried all above mentioned solution, but it's not working , Kindly give solution of this problem Razorpay team.

**Comment by ajay-zartek** [comment]
Have the same issue.

**Comment by Nishant3007** [comment]
> i'm also facing same issue, tried all above mentioned solution, but it's not working , Kindly give solution of this problem Razorpay team.

any solution u have found?

**Comment by harshuhere01** [comment]
> 

yes , in my case , the issue is backend developer doesn't changed RazorPay api_key , that's why when i'm trying to open razorpay it causes errors. so verify your RazoPay API_KEY in frontend side and backend side. if found different add same key.

**Comment by Nishant3007** [comment]
> Have the same issue.

Please check with your backend dev or check at ur end if u r the one by making the live mode on razorpay u have to generate the new key make these changes and all rest things are working
