### ISSUE TITLE
Memory leaks in version 1.3.0

### ISSUE THREAD

**Issue by mage1k99** [razorpay/razorpay-flutter#252]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I'm using the latest version of razorpay_flutter plugin which is 1.3.0 at this time. I'm facing memory leak issue in razorpay. there is already and issue #148 where the issue was addressed as fixed but it is not fixed. I even cleared the event listners in the dispose block but it did not help

![image](https://user-images.githubusercontent.com/46259860/176762063-14389a4b-94c6-45a2-9e9f-08cf11773f70.png)

Error log
```log
E/ActivityThread(12236): Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.O_$v$@8a0aa79 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(12236): android.app.IntentReceiverLeaked: Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.O_$v$@8a0aa79 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(12236):        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1588)
E/ActivityThread(12236):        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1368)
E/ActivityThread(12236):        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1515)
E/ActivityThread(12236):        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1488)
E/ActivityThread(12236):        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:640)
E/ActivityThread(12236):        at com.razorpay.G$_X_.onFinish(CheckoutPresenterImpl.java:857)
E/ActivityThread(12236):        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
E/ActivityThread(12236):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/ActivityThread(12236):        at android.os.Looper.loop(Looper.java:214)
E/ActivityThread(12236):        at android.app.ActivityThread.main(ActivityThread.java:7356)
E/ActivityThread(12236):        at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(12236):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/ActivityThread(12236):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

## Flutter Version :
3.0.2

## VScode Version :
Version: 1.69.0-insider

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create razorpay instance in initState as razorpay instance should be opened when the widget is built
2. Add event listeners for success and failure
3. Cancel the payment by clicking the X at the top of dialog
4. And memory leak, I use dialog box to display the error

## Expected Results
There should not be any memory leak

**Comment by mage1k99** [comment]
The memory leak only comes when you try to show dialog box instead of navigating to seperate screen to show the error.
