### ISSUE TITLE
App crash on rezorpay open

### ISSUE THREAD

**Issue by rohitbarge** [razorpay/razorpay-flutter#305]
error which i am getting 

Recording user engagement, ms: 1421
E/flutter ( 6569): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'Map<dynamic, dynamic>?' in type cast
E/flutter ( 6569): #0      PaymentFailureResponse.fromMap (package:razorpay_flutter/razorpay_flutter.dart:150:44)
E/flutter ( 6569): #1      Razorpay._handleResult (package:razorpay_flutter/razorpay_flutter.dart:72:42)
E/flutter ( 6569): #2      Razorpay.open (package:razorpay_flutter/razorpay_flutter.dart:54:5)

**Comment by vivekshindhe** [comment]
@rohitbarge Can you also provide version and payload and also the code snippet for the open call.

**Comment by alok2811** [comment]
Any solution for it
