### ISSUE TITLE
CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP

### ISSUE THREAD

**Issue by devsigofficial** [razorpay/razorpay-flutter#375]
Fatal Exception: java.lang.SecurityException: com.devsig.trustride: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3182)
       at android.os.Parcel.createException(Parcel.java:3166)
       at android.os.Parcel.readException(Parcel.java:3149)
       at android.os.Parcel.readException(Parcel.java:3091)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5784)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1853)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1781)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:756)
       at com.razorpay.CheckoutPresenterImpl.startSmsRetrieverForSavedCardsOTP(CheckoutPresenterImpl.java:884)
       at com.razorpay.CheckoutPresenterImpl.access$600(CheckoutPresenterImpl.java:59)
       at com.razorpay.G$_X_.onFinish(CheckoutPresenterImpl.java:863)
       at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:142)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

[com.devsig.trustride_issue_03efb6382bc82d7db8790586e253780b_crash_session_662158A7011A00016ED4A7B0ABCD7668_DNE_0_v2_stacktrace.txt](https://github.com/razorpay/razorpay-flutter/files/15042825/com.devsig.trustride_issue_03efb6382bc82d7db8790586e253780b_crash_session_662158A7011A00016ED4A7B0ABCD7668_DNE_0_v2_stacktrace.txt)

**Comment by vivekshindhe** [comment]
@devsigofficial Hey, we were able to reproduce the issue. Although it wasn't a fatal error, we could add the flags required. This will be released on Monday 22nd Apr, 23. Will update here once released. Thank you for bringing this to our attention.
