### ISSUE TITLE
Plugin Upgrade for breaking changes in Latest stable SDK 1.12

### ISSUE THREAD

**Issue by ajsatam** [razorpay/razorpay-flutter#60]
If I integrate this plugin with other plugins created with SDK 1.12 it gives the below error as there are breaking changes introduced in the latest Flutter SDK release. 

Please find below the Flutter links specifying this. 
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration
https://flutter.dev/docs/development/packages-and-plugins/developing-packages

The error I'm getting
```
E/MethodChannel#razorpay_flutter(20284): Failed to handle method call
E/MethodChannel#razorpay_flutter(20284): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/MethodChannel#razorpay_flutter(20284): 	at android.content.ComponentName.<init>(ComponentName.java:131)
E/MethodChannel#razorpay_flutter(20284): 	at android.content.Intent.<init>(Intent.java:6522)
E/MethodChannel#razorpay_flutter(20284): 	at com.razorpay.razorpay_flutter.RazorpayDelegate.openCheckout(RazorpayDelegate.java:51)
E/MethodChannel#razorpay_flutter(20284): 	at com.razorpay.razorpay_flutter.RazorpayFlutterPlugin.onMethodCall(RazorpayFlutterPlugin.java:42)
E/MethodChannel#razorpay_flutter(20284): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#razorpay_flutter(20284): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#razorpay_flutter(20284): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#razorpay_flutter(20284): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#razorpay_flutter(20284): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#razorpay_flutter(20284): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#razorpay_flutter(20284): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/MethodChannel#razorpay_flutter(20284): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#razorpay_flutter(20284): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/MethodChannel#razorpay_flutter(20284): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter (20284): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference, null) 
```

**Comment by sumedht** [comment]
@ajsatam We are on fixing this issue and updating SDK with latest platform version. Will let you know once it is done.

**Comment by ajsatam** [comment]
Thank you so much. Can you possibly tell me the ETA so we'll accordingly plan other activities.

**Comment by harshsoni1110** [comment]
Is it resolved? I'm facing the same issue.

**Comment by ajsatam** [comment]
The issue still persists in the new version 1.1.4

**Comment by sumedht** [comment]
We have updated SDK to version 1.2.1 which supports Flutter's 1.12 version changes. Please updated to latest version of SDK to fix this.
