### ISSUE TITLE
app crash when click on _razorpay.open(options) in release mode

### ISSUE THREAD

**Issue by dhsont** [razorpay/razorpay-flutter#93]
## Description
App is crashing when click on     ```_razorpay.open(options)```     in release mode   "  flutter build apk --split-per-abi"
It is working fine in debug mode.

error
```

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.razorpay.razorpay_flutter_example/com.razorpay.CheckoutActivity}: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.G_G" on path: DexPathList[[zip file "/data/app/com.razorpay.razorpay_flutter_example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.razorpay.razorpay_flutter_example-1/lib/arm, /data/app/com.razorpay.razorpay_flutter_example-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2808)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.razorpay.G_G" on path: DexPathList[[zip file "/data/app/com.razorpay.razorpay_flutter_example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.razorpay.razorpay_flutter_example-1/lib/arm, /data/app/com.razorpay.razorpay_flutter_example-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:74)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.razorpay.h_y.G_G(:1100)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.razorpay.P.<clinit>(:34)
	at com.razorpay.P.a()
	at com.razorpay.e.f(:4)
	at com.razorpay.m.d(:2)
	at com.razorpay.Ra.onCreate(:11)
	at com.razorpay.h.onCreate(:13)
	at com.razorpay.CheckoutActivity.onCreate(:1)
	at android.app.Activity.performCreate(Activity.java:6845)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2700)
	... 9 more
```

## Flutter Doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.900], locale en-IN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.47.1)
[√] Connected device (1 available)  

## Steps To Reproduce
Download razorpay-flutter plugin -> go to example folder -> run pub get  
then run command ```flutter build apk --split-per-abi```

you will get apk install it in your device after loading app click on "Open" button. App will exit.

**Comment by d3fkon** [comment]
It works fine when you run `flutter run --release` but crashes when built in release mode. 
My team is on the verge of switching payment gateways because of this bug. An acknowledgement regarding this would help us convince the team to stick with RP

**Comment by aliasgarlabs** [comment]
https://github.com/razorpay/razorpay-flutter/issues/42

**Comment by sumedht** [comment]
@dhsont U need to add proguard rules as given in razorpay doc [here](https://razorpay.com/docs/payment-gateway/android-integration/standard/proguard-rules/) & enable proguard in the build.
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
